# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.provider "virtualbox" do |v|
    v.memory = 4196
    v.cpus = 2
  end
  config.vm.box = "ubuntu/vivid64"
  # config.vm.box_check_update = false

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../", "/workflows"

  config.vm.provision "requirements", type: "shell", path: "requirements.sh"
  config.vm.provision "cwl", type: "shell", path: "setup_cwl.sh"
  config.vm.provision "cwl-test", type: "shell", path: "test_cwl.sh"
  #config.vm.provision "cwl", type:"shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  #SHELL
end
