FROM ubuntu:15.04
MAINTAINER Andrey V Kartashov "porter@porter.st"
COPY ./fastx_toolkit/bin/* /usr/local/bin/
#RUN apt-get update && apt-get install -y --no-install-recommends \
#    libssl1.0.0 \
#    && rm -rf /var/lib/apt/lists/*
