#!/usr/bin/env cwl-runner
#
# Authors: farahk@student.unimelb.edu.au and skanwal@student.unimelb.edu.au UNIVERSITY OF MELBOURNE
# Developed for CWL consortium http://commonwl.org/

class: Workflow

inputs:
  - id: "#reference"
    type: File
    description: reference human genome file 

  - id: "#PicardJarFile"
    type: File
    description: link to the picard.jar file
    
  - id: "#outputFileName_markDups"
    type: string
    description: output file name generated as a result of Markduplicates command from picard toolkit
    
  - id: "#metricsFile"
    type: string
    description: metric file generated by MarkDupicates command listing duplicates

  - id: "#readSorted"
    type: string
    description: set to be true showing that reads are sorted already

  - id: "#removeDuplicates"
    type: string
    description: set to be true
 
  - id: "#outputfile_realignTarget"
    type: string
    description: name of realignTargetCreator output file

  - id: "#inputFileName_markDups"
    type: File
    description: bam input for markdups from previous step   
    
  - id: "#createIndex"
    type: string
    description: set to be true to create .bai file

  - id: "#known"
    type:
      - "null"
      - type: array
        items: File
    description: array of known variant files for realign target creator

outputs:

  - id: "#markDups_output"
    type: File
    source: "#markDups.markDups_output"
    
  - id: "#output_realignTarget"
    type: File
    source: "#RealignTarget.output_realignTarget" 

requirements:
  - import: node-engine.cwl
  - import: envvar-global.cwl

steps:
      
  - id: "#markDups"
    run: { import: markDups.cwl }
    inputs:
      - { id: "#markDups.jar_file", source: "#PicardJarFile" }
      - { id: "#markDups.outputFileName_markDups", source: "#outputFileName_markDups" }
      - { id: "#markDups.inputFileName_markDups", source: "#inputFileName_markDups" }
      - { id: "#markDups.metricsFile", source: "#metricsFile" }
      - { id: "#markDups.readSorted", source: "#readSorted" }
      - { id: "#markDups.removeDuplicates", source: "#removeDuplicates" } 
      - { id: "#markDups.createIndex", source: "#createIndex" } 
      
    outputs:
      - { id: "#markDups.markDups_output" }

  - id: "#RealignTarget"
    run: { import: realignTargetCreator.cwl }
    inputs:
      - { id: "#RealignTarget.outputfile_realignTarget", source: "#outputfile_realignTarget" }
      - { id: "#RealignTarget.inputBam_realign", source: "#markDups.markDups_output" }
      - { id: "#RealignTarget.reference", source: "#reference" }
      - { id: "#RealignTarget.known", source: "#known" }
      
    outputs:
      - { id: "#RealignTarget.output_realignTarget" }
