database.dna :  seq1.rna seq2.rna seq3.rna
	cat seq1.rna seq2.rna seq3.rna | tr "U" "T" > database.dna && echo "Done"

seq3.rna :
	echo "AUGAAGACUGACUCGAUCGAUCG" > seq3.rna

seq2.rna :
	echo "AUGAAGACUGACUCGAUCGAUCG" > seq2.rna

seq1.rna :
	echo "AUGAAGACUGACUCGAUCGAUCG" > seq1.rna
