class: schema:CreativeWork

schema:name: "Common Workflow Language"
schema:url: http://commonwl.org/
schema:license: http://www.apache.org/licenses/LICENSE-2.0

schema:workExample:
- class: schema:SoftwareSourceCode
  schema:codeRepository: https://github.com/common-workflow-language/workflows

schema:schemaVersion: http://common-workflow-language.github.io/draft-3/

schema:author:
- class: schema:Organization
  schema:name: "Curoverse"
  schema:member:
  - class: schema:Person
    id: "http://orcid.org/0000-0003-3566-7705"
    schema:name: "Peter Amstutz"
    schema:email: "mailto:peter.amstutz@curoverse.com"
- class: schema:Organization
  schema:name: "Seven Bridges Genomics"
  schema:member:
  - class: schema:Person
    id: "mailto:nebojsa.tijanic@sbgenomics.com"
    schema:name: "Nebojša Tijanić"
    schema:email: "mailto:nebojsa.tijanic@sbgenomics.com"

schema:contributor:
- class: schema:Organization
  schema:name: "Seven Bridges Genomics"
  schema:member:
  - class: schema:Person
    schema:name: "Luka Stojanovic"
    schema:email: "mailto:luka.stojanovic@sbgenomics.com"
- class: schema:Organization
  schema:name: "Galaxy Project, Pennsylvania State University"
  schema:member:
  - class: schema:Person
    schema:name: "John Chilton"
    schema:email: "mailto:jmchilton@gmail.com"
- class: schema:Organization
  schema:name: "University of California, Davis"
  schema:member:
  - class: schema:Person
    schema:name: "Michael R. Crusoe"
    schema:email: "mailto:crusoe@ucdavis.edu"
- class: schema:Organization
  schema:name: "Institut Pasteur"
  schema:member:
  - class: schema:Person
    schema:name: "Hervé Ménager"
    schema:email: "mailto:herve.menager@gmail.com"
- class: schema:Organization
  schema:name: "BioDatomics"
  schema:member:
  - class: schema:Person
    schema:name: "Maxim Mikheev"
    schema:email: "mailto:mikhmv@biodatomics.com"
- class: schema:Organization
  schema:name: "University of Manchester"
  schema:member:
  - class: schema:Person
    schema:name: "Stian Soiland-Reyes"
    schema:email: "mailto:soiland-reyes@cs.manchester.ac.uk"